/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material Design 3 Color System (POC: baawa_centre_de_commandement_profil_connect)
        'primary': '#3B82F6',
        'primary-hover': '#2563EB',
        'primary-dark': '#2563EB',
        'on-primary': '#ffffff',
        'primary-container': '#3B82F6',
        'on-primary-container': '#86a0cd',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#adc7f7',
        'on-primary-fixed': '#001b3c',
        'on-primary-fixed-variant': '#2d476f',
        'inverse-primary': '#adc7f7',

        'secondary': '#10B981',
        'on-secondary': '#ffffff',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#00714d',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',

        'tertiary': '#361900',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#552b00',
        'on-tertiary-container': '#eb851c',
        'tertiary-fixed': '#ffdcc3',
        'tertiary-fixed-dim': '#ffb77d',
        'on-tertiary-fixed': '#2f1500',
        'on-tertiary-fixed-variant': '#6e3900',

        'error': '#EF4444',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        'background': '#F1F5F9',
        'on-background': '#0F172A',
        'surface': '#ffffff',
        'on-surface': '#0F172A',
        'surface-dim': '#dad9dd',
        'surface-bright': '#FFFFFF',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#F1F5F9',
        'surface-container': '#F8FAFC',
        'surface-container-high': '#E2E8F0',
        'surface-container-highest': '#e3e2e6',
        'surface-variant': '#E2E8F0',
        'on-surface-variant': '#64748B',

        'outline': '#E2E8F0',
        'outline-variant': '#c4c6cf',

        'inverse-surface': '#2f3033',
        'inverse-on-surface': '#f1f0f4',
        'surface-tint': '#3B82F6',
      },
      fontFamily: {
        headline: ['Montserrat', 'Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'xs': '0.25rem',
        'sm': '0.375rem',
        'md': '0.5rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      backdropFilter: {
        'blur-sm': 'blur(4px)',
        'blur': 'blur(8px)',
        'blur-md': 'blur(12px)',
        'blur-lg': 'blur(16px)',
        'blur-xl': 'blur(20px)',
      },
      boxShadow: {
        'sm': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        'md': '0 4px 6px -1px rgb(0 0 0 / 0.1)',
        'lg': '0 10px 15px -3px rgb(0 0 0 / 0.1)',
        'xl': '0 20px 25px -5px rgb(0 0 0 / 0.1)',
      },
    },
  },
  plugins: [],
}
